version: 0.1
component: build
shell: bash
steps:
  - type: Command
    name: Maven Build
    command: mvn clean package -DskipTests
  - type: Command
    name: Docker Build
    command: docker build -t ${OCIR_REPO}/java-svc:latest .
  - type: Command
    name: Docker Push
    command: |
      echo "Logging in to OCIR..."
      docker login ${OCIR_REPO} -u '${OCI_USERNAME}' -p '${OCI_AUTH_TOKEN}'
      docker push ${OCIR_REPO}/java-svc:latest
