version: 0.1
component: build
shell: bash
steps:
  - type: Command
    name: Maven Build
    command: mvn clean package -DskipTests
  - type: Command
    name: Docker Build
    command: docker build -t ${TOCIR_REPO}/java-svc:latest .
  - type: Command
    name: Docker Push
    command: |
      echo "Logging in to OCIR..."
      docker login ${TOCIR_REPO} -u '${TOCI_USERNAME}' -p '${TOCI_AUTH_TOKEN}'
      docker push ${TOCIR_REPO}/java-svc:latest
