version: 0.1
component: build
timeoutInSeconds: 1800
shell: bash
runAsUser: root

env:
  variables:
    REGION: "iad"  # Replace with your region
    TENANCY_NS: "idxib5yhfi1u"
    REPO_NAME: "pandoc-images"
    IMAGE_TAG: "pandoc-latex"
    DOCKER_IMAGE: "iad.ocir.io/${TENANCY_NS}/${REPO_NAME}:${IMAGE_TAG}"

steps:
  - type: Command
    name: Build Docker Image
    command: |
      docker build -t ${DOCKER_IMAGE} .

  - type: Command
    name: Login to OCIR
    command: |
      echo "ViEt]3XNm{7W+VqE4G(P" | docker login iad.ocir.io \
        -u "hcsops/shilpi.agrawal@oracle.com" --password-stdin

  - type: Command
    name: Push Image to OCIR
    command: |
      docker push ${DOCKER_IMAGE}
